# Proyecto Final Algoritmos y Estructura de Datos
# Base de Datos Python - NEO4J
# Oliver Josué de León Milian 19270
# Julio Roberto Herrera Saban 19402
# In collaboration with Laura Tamath 19365

from neo4j import GraphDatabase

# Python - neo4j connection is available
db = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "uvg123"),encrypted=False)
session = db.session()

# Taste label and nodes are created
a =  "CREATE (SPICY:TASTE{name:'Spicy'}),(SALTY:TASTE{name:'Salty'}),(SWEET:TASTE{name:'Sweet'}),"
a += "(SOUR:TASTE{name:'Sour'}),(BITTER:TASTE{name:'Bitter'}),(UMAMI:TASTE{name:'Umami'}),"

# Ingredients label and nodes are created
a += "(BUTTER:INGREDIENTS{name:'Butter'}),(FLOUR:INGREDIENTS{name:'Flour'}),(HAM:INGREDIENTS{name:'Ham'}),"
a += "(OIL:INGREDIENTS{name:'Oil'}),(BACON:INGREDIENTS{name:'Bacon'}),(BEEF:INGREDIENTS{name:'Beef'}),"
a += "(CHICKEN:INGREDIENTS{name:'Chicken'}),(CREAM:INGREDIENTS{name:'Cream'}),(CHEESE:INGREDIENTS{name:'Cheese'}),"
a += "(EGGS:INGREDIENTS{name:'Eggs'}),(POTATO:INGREDIENTS{name:'Potato'}),(MILK:INGREDIENTS{name:'Milk'}),"
a += "(SALT:INGREDIENTS{name:'Salt'}),(APPLE:INGREDIENTS{name:'Apple'}),(BREAD:INGREDIENTS{name:'Bread'}),"
a += "(LEMON:INGREDIENTS{name:'Lemon'}),(SUGAR:INGREDIENTS{name:'Sugar'}),(WATER:INGREDIENTS{name:'Water'}),"
a += "(BANANA:INGREDIENTS{name:'Banana'}),(STRAWBERRY:INGREDIENTS{name:'Strawberry'}),(SALMON:INGREDIENTS{name:'Salmon'}),"
a += "(NOODLES:INGREDIENTS{name:'Noodles'}),(PASTA:INGREDIENTS{name:'Pasta'}),(TOMATO:INGREDIENTS{name:'Tomato'}),"
a += "(ONION:INGREDIENTS{name:'Onion'}),(LETTUCE:INGREDIENTS{name:'Lettuce'}),"

# Styles label and nodes are created
a += "(BOILED:STYLES{name:'Boiled'}),(BAKED:STYLES{name:'Baked'}),(FRIED:STYLES{name:'Fried'}),"
a += "(BROILED:STYLES{name:'Broiled'}),(GRATINED:STYLES{name:'Gratined'}),(SIMMERED:STYLES{name:'Simmered'}),"
a += "(CARAMELISED:STYLES{name:'Caramelised'}),(GLACED:STYLES{name:'Glaced'}),(BARBECUED:STYLES{name:'Barbecued'}),"

# Kind label and nodes are created
a += "(BEVERAGE:KIND{name:'Beverage'}),(DESSERT:KIND{name:'Dessert'}),(LIGHT:KIND{name:'Light'}),"
a += "(MAINCOURSE:KIND{name:'Main Course'}),(FIRSTCOURSE:KIND{name:'First Course'}),"

# Meal label and nodes are created
a += "(SPAGHETTI:MEAL{name:'Spaghetti'}),(GREEKSALAD:MEAL{name:'Greek Salad'}),(FRENCHFRIES:MEAL{name:'French Fries'}),"
a += "(AMERICANHAMBURGER:MEAL{name:'American Hamburger'}),(STRAWBERRYCAKE:MEAL{name:'Strawberry Cake'}),(SANDWICH:MEAL{name:'Sandwich'}),"
a += "(CLASSICHAMBURGER:MEAL{name:'Classic Hamburger'}),(BANANAMILKSHAKE:MEAL{name:'Banana MilkShake'}),(FRUITJUICE:MEAL{name:'Fruit Juice'}),"
a += "(COOKIES:MEAL{name:'Cookies'}),(TOMATOSOUP:MEAL{name:'Tomato Soup'}),(MASHEDPOTATOES:MEAL{name:'Mashed Potatoes'}),"
a += "(SALMONMEAL:MEAL{name:'Salmon Meal'}),(BROILEDCHICKEN:MEAL{name:'Broiled Chicken'}),(TACOS:MEAL{name:'Tacos'}),"
a += "(ITALIANPIZZA:MEAL{name:'Italian Pizza'}),(RICENOODLES:MEAL{name:'Rice Noodles'}),(SUSHI:MEAL{name:'Sushi'}),"
a += "(COCKTAILS:MEAL{name:'Cocktails'}),(TOSSEDSALAD:MEAL{name:'Tossed Salad'}),(MEATBALLS:MEAL{name:'Meatballs'}),"
a += "(LEMONADE:MEAL{name:'Lemonade'}),(MACNCHEESE:MEAL{name:'Mac&Cheese'}),(CHICKENSOUP:MEAL{name:'Chicken Soup'}),"
a += "(SANTAFESALAD:MEAL{name:'SantaFe Salad'}),(PANCAKES:MEAL{name:'Pancakes'}),(ONIONRINGS:MEAL{name:'Onion Rings'}),"


#Spaghetti Relationships
a += "(SPAGHETTI)-[A:IS_A]->(MAINCOURSE),(PASTA)-[B:IS_USED_IN]->(SPAGHETTI),(OIL)-[C:IS_USED_IN]->(SPAGHETTI),(TOMATO)-[D:IS_USED_IN]->(SPAGHETTI),"
a += "(ONION)-[E:IS_USED_IN]->(SPAGHETTI),(WATER)-[F:IS_USED_IN]->(SPAGHETTI),(SPAGHETTI)-[G:METHOD]->(BOILED),(SPAGHETTI)-[H:TASTE]->(SALTY),"
a += "(SPAGHETTI)-[I:TASTE]->(UMAMI),(SPAGHETTI)-[J:TASTE]->(SOUR),(SPAGHETTI)-[K:METHOD]->(GRATINED),"

#Greek Salad Relationships
a += "(GREEKSALAD)-[A1:IS_A]->(MAINCOURSE),(GREEKSALAD)-[B1:IS_A]->(FIRSTCOURSE),(GREEKSALAD)-[B1100:IS_A]->(LIGHT),(LETTUCE)-[C1:IS_USED_IN]->(GREEKSALAD),"
a += "(CHICKEN)-[E1:IS_USED_IN]->(GREEKSALAD),(BREAD)-[D1:IS_USED_IN]->(GREEKSALAD),(CHEESE)-[F1:IS_USED_IN]->(GREEKSALAD),(GREEKSALAD)-[G1:TASTE]->(SALTY),"
a += "(GREEKSALAD)-[H1:TASTE]->(UMAMI),"

#French Fries Relationships
a += "(FRENCHFRIES)-[A2:IS_A]->(FIRSTCOURSE),(POTATO)-[B2:IS_USED_IN]->(FRENCHFRIES),(OIL)-[C2:IS_USED_IN]->(FRENCHFRIES),"
a += "(FRENCHFRIES)-[D2:TASTE]->(SALTY),(FRENCHFRIES)-[E2:TASTE]->(UMAMI),(FRENCHFRIES)-[F2:METHOD]->(FRIED),"

#American Hamburger Relationships
a += "(AMERICANHAMBURGER)-[A3:IS_A]->(MAINCOURSE),(BREAD)-[B3:IS_USED_IN]->(AMERICANHAMBURGER),(LETTUCE)-[C3:IS_USED_IN]->(AMERICANHAMBURGER),"
a += "(CHEESE)-[D3:IS_USED_IN]->(AMERICANHAMBURGER),(BEEF)-[E300:IS_USED_IN]->(AMERICANHAMBURGER),(BACON)-[E3:IS_USED_IN]->(AMERICANHAMBURGER),"
a += "(TOMATO)-[F3:IS_USED_IN]->(AMERICANHAMBURGER),(ONION)-[G3:IS_USED_IN]->(AMERICANHAMBURGER),(AMERICANHAMBURGER)-[H3:TASTE]->(UMAMI),"
a += "(AMERICANHAMBURGER)-[I3:TASTE]->(SALTY),(FRENCHFRIES)-[J3:METHOD]->(BROILED),"

#Strawberry Cake Relationships
a += "(STRAWBERRYCAKE)-[A4:IS_A]->(DESSERT),(FLOUR)-[B4:IS_USED_IN]->(STRAWBERRYCAKE),(MILK)-[C4:IS_USED_IN]->(STRAWBERRYCAKE),"
a += "(STRAWBERRY)-[D4:IS_USED_IN]->(STRAWBERRYCAKE),(SUGAR)-[E4:IS_USED_IN]->(STRAWBERRYCAKE),(CREAM)-[F4:IS_USED_IN]->(STRAWBERRYCAKE),"
a += "(BUTTER)-[G4:IS_USED_IN]->(STRAWBERRYCAKE),(EGGS)-[H4:IS_USED_IN]->(STRAWBERRYCAKE),(STRAWBERRYCAKE)-[I4:METHOD]->(BAKED),"
a += "(STRAWBERRYCAKE)-[J4:TASTE]->(SWEET),"

#Sandwich Relationships
a += "(SANDWICH)-[A5:IS_A]->(MAINCOURSE),(SANDWICH)-[B5:IS_A]->(LIGHT),(BREAD)-[C5:IS_USED_IN]->(SANDWICH),(LETTUCE)-[D5:IS_USED_IN]->(SANDWICH),"
a += "(HAM)-[E5:IS_USED_IN]->(SANDWICH),(CHEESE)-[F5:IS_USED_IN]->(SANDWICH),(TOMATO)-[G5:IS_USED_IN]->(SANDWICH),(SANDWICH)-[H5:TASTE]->(UMAMI),"

#Classic Hamburger Relationships
a += "(CLASSICHAMBURGER)-[A6:IS_A]->(MAINCOURSE),(BREAD)-[B6:IS_USED_IN]->(CLASSICHAMBURGER),(CHICKEN)-[C6:IS_USED_IN]->(CLASSICHAMBURGER),"
a += "(LETTUCE)-[D6:IS_USED_IN]->(CLASSICHAMBURGER),(TOMATO)-[E6:IS_USED_IN]->(CLASSICHAMBURGER),(CLASSICHAMBURGER)-[F6:METHOD]->(BROILED),"
a += "(CLASSICHAMBURGER)-[G6:TASTE]->(UMAMI),"

#Banana MilkShake Relationships
a += "(BANANAMILKSHAKE)-[A7:IS_A]->(BEVERAGE),(MILK)-[B7:IS_USED_IN]->(BANANAMILKSHAKE),(BANANA)-[C7:IS_USED_IN]->(BANANAMILKSHAKE),"
a += "(SUGAR)-[D7:IS_USED_IN]->(BANANAMILKSHAKE),(BANANAMILKSHAKE)-[E7:TASTE]->(SWEET),"

#Fruit Juice Relationships
a += "(FRUITJUICE)-[A8:IS_A]->(BEVERAGE),(WATER)-[B8:IS_USED_IN]->(FRUITJUICE),(STRAWBERRY)-[C8:IS_USED_IN]->(FRUITJUICE),"
a += "(APPLE)-[D8:IS_USED_IN]->(FRUITJUICE),(SUGAR)-[E8:IS_USED_IN]->(FRUITJUICE),(BANANA)-[F8:IS_USED_IN]->(FRUITJUICE),(FRUITJUICE)-[G8:TASTE]->(SWEET),"

#Cookies Relationships
a += "(COOKIES)-[A9:IS_A]->(DESSERT),(BUTTER)-[B9:IS_USED_IN]->(COOKIES),(SUGAR)-[C9:IS_USED_IN]->(COOKIES),(COOKIES)-[D9:TASTE]->(SWEET),"
a += "(MILK)-[E9:IS_USED_IN]->(COOKIES),(FLOUR)-[F9:IS_USED_IN]->(COOKIES),(EGGS)-[G9:IS_USED_IN]->(COOKIES),(COOKIES)-[D900:METHOD]->(BAKED),"

#Tomato Soup Relationship
a += "(TOMATOSOUP)-[A10:IS_A]->(MAINCOURSE),(TOMATOSOUP)-[B10:IS_A]->(FIRSTCOURSE),(TOMATOSOUP)-[C10:IS_A]->(LIGHT),"
a += "(TOMATOSOUP)-[D10:TASTE]->(UMAMI),(TOMATOSOUP)-[E10:TASTE]->(SOUR),(TOMATO)-[F10:IS_USED_IN]->(TOMATOSOUP),(WATER)-[G10:IS_USED_IN]->(TOMATOSOUP),"
a += "(SALT)-[H10:IS_USED_IN]->(TOMATOSOUP),(TOMATOSOUP)-[I10:METHOD]->(BOILED),"

#Mashed Potatoes Relationships
a += "(MASHEDPOTATOES)-[A11:IS_A]->(MAINCOURSE),(MASHEDPOTATOES)-[B11:IS_A]->(FIRSTCOURSE),(TOMATOSOUP)-[C11:IS_A]->(LIGHT),"
a += "(MASHEDPOTATOES)-[D11:TASTE]->(UMAMI),(MASHEDPOTATOES)-[E11:TASTE]->(SALTY),(TOMATO)-[F11:IS_USED_IN]->(MASHEDPOTATOES),"
a += "(MILK)-[G11:IS_USED_IN]->(MASHEDPOTATOES),(POTATO)-[H11:IS_USED_IN]->(MASHEDPOTATOES),(SALT)-[I11:IS_USED_IN]->(MASHEDPOTATOES),"
a += "(MASHEDPOTATOES)-[J11:METHOD]->(BOILED),"

#Salmon Meal Relationships
a += "(SALMONMEAL)-[A12:IS_A]->(MAINCOURSE),(SALMONMEAL)-[B12:IS_A]->(LIGHT),(SALMONMEAL)-[C12:TASTE]->(SALTY),"
a += "(SALMONMEAL)-[D12:TASTE]->(BITTER),(SALMON)-[E12:IS_USED_IN]->(SALMONMEAL),(SALT)-[F12:IS_USED_IN]->(SALMONMEAL),"
a += "(ONION)-[G12:IS_USED_IN]->(SALMONMEAL),(LEMON)-[H12:IS_USED_IN]->(SALMONMEAL),(SALMONMEAL)-[I12:TASTE]->(SOUR),"
a += "(SALMONMEAL)-[J12:METHOD]->(FRIED),(SALMONMEAL)-[K12:METHOD]->(BOILED),(SALMONMEAL)-[M12:METHOD]->(SIMMERED),"

#Broiled Chicken Relationships
a += "(BROILEDCHICKEN)-[A13:IS_A]->(MAINCOURSE),(BROILEDCHICKEN)-[B130:TASTE]->(SALTY),(CHICKEN)-[C13:IS_USED_IN]->(BROILEDCHICKEN),"
a += "(SALT)-[D13:IS_USED_IN]->(BROILEDCHICKEN),(LEMON)-[D1300:IS_USED_IN]->(BROILEDCHICKEN),(BROILEDCHICKEN)-[B13:TASTE]->(SOUR),"
a += "(BROILEDCHICKEN)-[B1300:METHOD]->(BROILED),"

#Tacos Relationships
a += "(TACOS)-[A14:IS_A]->(MAINCOURSE),(TACOS)-[B14:IS_A]->(FIRSTCOURSE),(TACOS)-[C14:TASTE]->(SALTY),(CHICKEN)-[D14:IS_USED_IN]->(TACOS),"
a += "(ONION)-[E14:IS_USED_IN]->(TACOS),(TOMATO)-[F14:IS_USED_IN]->(TACOS),(LEMON)-[G14:IS_USED_IN]->(TACOS),(BEEF)-[H14:IS_USED_IN]->(TACOS),"
a += "(SALT)-[I14:IS_USED_IN]->(TACOS),(TACOS)-[J14:METHOD]->(BROILED),"

#Italian Pizza Relationships
a += "(ITALIANPIZZA)-[A15:IS_A]->(MAINCOURSE),(ITALIANPIZZA)-[B15:TASTE]->(SALTY),(ITALIANPIZZA)-[C15:TASTE]->(UMAMI),"
a += "(TOMATO)-[D15:IS_USED_IN]->(ITALIANPIZZA),(FLOUR)-[E15:IS_USED_IN]->(ITALIANPIZZA),(HAM)-[F15:IS_USED_IN]->(ITALIANPIZZA),"
a += "(CHEESE)-[G15:IS_USED_IN]->(ITALIANPIZZA),(ONION)-[H15:IS_USED_IN]->(ITALIANPIZZA),(ITALIANPIZZA)-[I15:METHOD]->(BAKED),"

#Rice Noodles Relationships
a += "(RICENOODLES)-[A16:IS_A]->(MAINCOURSE),(RICENOODLES)-[B16:TASTE]->(SALTY),(NOODLES)-[C16:IS_USED_IN]->(RICENOODLES),"
a += "(WATER)-[D16:IS_USED_IN]->(RICENOODLES),(RICENOODLES)-[E16:METHOD]->(BOILED),"

#Onion Rings Relationships
a += "(ONIONRINGS)-[A17:IS_A]->(FIRSTCOURSE),(CHEESE)-[B17:IS_USED_IN]->(ONIONRINGS),(BREAD)-[C17:IS_USED_IN]->(ONIONRINGS),"
a += "(EGGS)-[D17:IS_USED_IN]->(ONIONRINGS),(OIL)-[E17:IS_USED_IN]->(ONIONRINGS),(BUTTER)-[F17:IS_USED_IN]->(ONIONRINGS),"
a += "(ONIONRINGS)-[G17:TASTE]->(SALTY),"

#Pancakes relationships
a += "(PANCAKES)-[A18:IS_A]->(DESSERT),(BUTTER)-[B18:IS_USED_IN]->(PANCAKES),(FLOUR)-[C18:IS_USED_IN]->(PANCAKES),"
a += "(EGGS)-[D18:IS_USED_IN]->(PANCAKES),(BANANA)-[E18:IS_USED_IN]->(PANCAKES),(MILK)-[F18:IS_USED_IN]->(PANCAKES),"
a += "(PANCAKES)-[G18:TASTE]->(SWEET),"

#Santa Fe Salad Relationships
a += "(SANTAFESALAD)-[A19:IS_A]->(LIGHT),(OIL)-[B19:IS_USED_IN]->(SANTAFESALAD),(CHICKEN)-[C19:IS_USED_IN]->(SANTAFESALAD),"
a += "(LETTUCE)-[D19:IS_USED_IN]->(SANTAFESALAD),(ONION)-[E19:IS_USED_IN]->(SANTAFESALAD),(TOMATO)-[F19:IS_USED_IN]->(SANTAFESALAD),"
a += "(SANTAFESALAD)-[G19:TASTE]->(UMAMI),"

#Chicken Soup Relationships
a += "(CHICKENSOUP)-[A20:IS_A]->(FIRSTCOURSE),(CHICKEN)-[B20:IS_USED_IN]->(CHICKENSOUP),(ONION)-[C20:IS_USED_IN]->(CHICKENSOUP),"
a += "(MILK)-[D20:IS_USED_IN]->(CHICKENSOUP),"
a += "(CHICKENSOUP)-[E20:TASTE]->(SPICY),(CHICKENSOUP)-[F20:TASTE]->(SALTY),"

#Mac&Cheese Relationships
a += "(MACNCHEESE)-[A21:IS_A]->(MAINCOURSE),(CHEESE)-[B21:IS_USED_IN]->(MACNCHEESE),(NOODLES)-[C21:IS_USED_IN]->(MACNCHEESE),"
a += "(BUTTER)-[D21:IS_USED_IN]->(MACNCHEESE),(FLOUR)-[E21:IS_USED_IN]->(MACNCHEESE),(MILK)-[F21:IS_USED_IN]->(MACNCHEESE),(BREAD)-[G21:IS_USED_IN]->(MACNCHEESE),"
a += "(MACNCHEESE)-[H21:TASTE]->(UMAMI),(MACNCHEESE)-[I21:TASTE]->(SALTY),"

#Lemonade Relationships
a += "(LEMONADE)-[A22:IS_A]->(BEVERAGE),(SUGAR)-[B22:IS_USED_IN]->(LEMONADE),(LEMON)-[C22:IS_USED_IN]->(LEMONADE),"
a += "(WATER)-[D22:IS_USED_IN]->(LEMONADE),"
a += "(LEMONADE)-[E22:TASTE]->(SWEET),"


#Meatballs Relationships
a += "(MEATBALLS)-[A23:IS_A]->(MAINCOURSE),(EGGS)-[B23:IS_USED_IN]->(MEATBALLS),(TOMATO)-[C23:IS_USED_IN]->(MEATBALLS),"
a += "(MILK)-[D23:IS_USED_IN]->(MEATBALLS),(BEEF)-[E23:IS_USED_IN]->(MEATBALLS),(NOODLES)-[F23:IS_USED_IN]->(MEATBALLS),(CHEESE)-[G23:IS_USED_IN]->(MEATBALLS),"
a += "(MEATBALLS)-[H23:TASTE]->(SALTY),"

#Tossed Salad Relationships
a += "(TOSSEDSALAD)-[A24:IS_A]->(LIGHT),(LETTUCE)-[B24:IS_USED_IN]->(TOSSEDSALAD),(TOMATO)-[C24:IS_USED_IN]->(TOSSEDSALAD),"
a += "(ONION)-[C2400:IS_USED_IN]->(TOSSEDSALAD),(OIL)-[D24:IS_USED_IN]->(TOSSEDSALAD),(LEMON)-[E24:IS_USED_IN]->(TOSSEDSALAD),"
a += "(TOSSEDSALAD)-[F24:TASTE]->(UMAMI),"

#Cocktails Relationships lo pIS_USED_IN como si fuese mojito
a += "(COCKTAILS)-[A25:IS_A]->(BEVERAGE),(LEMON)-[B25:IS_USED_IN]->(COCKTAILS),(SUGAR)-[C25:IS_USED_IN]->(COCKTAILS),"
a += "(COCKTAILS)-[D25:TASTE]->(SWEET),"

#Shushii Relationships
a += "(SUSHI)-[A26:IS_A]->(MAINCOURSE),(SALMON)-[B26:IS_USED_IN]->(SUSHI),(TOMATO)-[C26:IS_USED_IN]->(SUSHI),"
a += "(SUSHI)-[D26:TASTE]->(SALTY)"

engine = a
session.run(engine)

db.close()